# Little nice utilities
brew "ack"
brew "asdf"
brew "bat"
brew "dust"
brew "fd"
brew "fswatch"
brew "fzf"
brew "gping"
brew "htop"
brew "mtr"
brew "ripgrep"
brew "tldr"
brew "tree"
brew "vale"
brew "wakeonlan"
brew "wordnet"

# Bigger applications
brew "ansible"
brew "exercism"
brew "exiftool"
brew "ffmpeg"
brew "fish"
brew "git"
brew "git-lfs"
brew "hashicorp/tap/terraform"
brew "imagemagick"
brew "neovim"
brew "newsboat"
brew "rbenv-gemset"
brew "tmux"

# Nerves (https://www.nerves-project.org/) utilities
brew "coreutils"
brew "fwup"
brew "pkg-config"
brew "squashfs"
brew "xz"
