require("nvim-treesitter.configs").setup({
  auto_install = vim.fn.executable "git" == 1 and vim.fn.executable "tree-sitter" == 1, -- only if git and tree-sitter available
  ignore_install = { "javascript" },
  ensure_installed = {
    "bash",
    "c",
    "css",
    "diff",
    "dockerfile",
    "elixir",
    "elm",
    "erlang",
    "fish",
    "git_config",
    "gitcommit",
    "gitignore",
    "heex",
    "html",
    "jsdoc",
    "json",
    "jsonc",
    "lua",
    "luadoc",
    "luap",
    "markdown",
    "markdown_inline",
    "mermaid",
    "python",
    "query",
    "regex",
    "ruby",
    "scss",
    "sql",
    "ssh_config",
    "svelte",
    "terraform",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "xml",
    "yaml"
  },
  highlight = {
    enable = true,
    disable = function(_lang, bufnr)
      return vim.api.nvim_buf_line_count(bufnr) > 50000
    end,
  },
})
